image: condaforge/mambaforge
tasks:
  - name: mamba env create and package install
    init: |
      mamba init
      . ${HOME}/.bashrc
      mamba env create -n dev_env -f environment.yml
      mamba activate dev_env
      pip install .
