image: condaforge/mambaforge
tasks:
  - name: mamba env create and package install
    init: |
      mamba init
      . ${HOME}/.bashrc
      mamba env create -f environment.yml python=3.9
      mamba activate dev_env
      pip install .
