image: mambaorg/micromamba
tasks:
  - name: mamba install
    init: |
      mamba install python=3.9 pip numpy dataclasses bioconda::taxonkit=0.12.0 conda-forge::networkx=2.6.3 pytest pytest-console-scripts
  - name: package install
    init: |
      pip install .
