name: dev_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - pip
  - numpy
  - dataclasses
  - bioconda::taxonkit=0.12.0
  - networkx=2.6.3
  - pytest
  - pytest-console-scripts
