name: gtdb_to_taxdump
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - pip
  - numpy
  - dataclasses
  - tqdm
  - taxonkit=0.12.0
  - networkx=2.6.3
  - pytest
  - pytest-console-scripts
